
// Category
export const LISTEN_TO_CATEGORIES_RECEIVED_DATA = 'LISTEN_TO_CATEGORIES_RECEIVED_DATA';
export const LISTEN_TO_CATEGORIES_STARTED = 'LISTEN_TO_CATEGORIES_STARTED';
export const LISTEN_TO_CATEGORY_RECEIVED_DATA = 'LISTEN_TO_CATEGORY_RECEIVED_DATA';
export const LISTEN_TO_CATEGORY_STARTED = 'LISTEN_TO_CATEGORY_STARTED';

//Product
export const LISTEN_TO_PRODUCTS_RECEIVED_DATA = 'LISTEN_TO_PRODUCTS_RECEIVED_DATA';
export const LISTEN_TO_PRODUCTS_STARTED = 'LISTEN_TO_PRODUCTS_STARTED';
export const LISTEN_TO_PRODUCT_RECEIVED_DATA = 'LISTEN_TO_PRODUCT_RECEIVED_DATA';
export const LISTEN_TO_PRODUCT_STARTED = 'LISTEN_TO_PRODUCT_STARTED';
