
// Category
export const LISTEN_TO_CATEGORIES_RECEIVED_DATA = 'LISTEN_TO_CATEGORIES_RECEIVED_DATA';
export const LISTEN_TO_CATEGORIES_STARTED = 'LISTEN_TO_CATEGORIES_STARTED';
export const LISTEN_TO_CATEGORY_RECEIVED_DATA = 'LISTEN_TO_CATEGORY_RECEIVED_DATA';
export const LISTEN_TO_CATEGORY_STARTED = 'LISTEN_TO_CATEGORY_STARTED';

//Product
export const LISTEN_TO_PRODUCTS_RECEIVED_DATA = 'LISTEN_TO_PRODUCTS_RECEIVED_DATA';
export const LISTEN_TO_PRODUCTS_STARTED = 'LISTEN_TO_PRODUCTS_STARTED';
export const LISTEN_TO_PRODUCT_RECEIVED_DATA = 'LISTEN_TO_PRODUCT_RECEIVED_DATA';
export const LISTEN_TO_PRODUCT_STARTED = 'LISTEN_TO_PRODUCT_STARTED';

//Shippings
export const LISTEN_TO_SHIPPINGS_RECEIVED_DATA = 'LISTEN_TO_SHIPPINGS_RECEIVED_DATA';
export const LISTEN_TO_SHIPPINGS_STARTED = 'LISTEN_TO_SHIPPINGS_STARTED';

//Provider
export const LISTEN_TO_PROVIDERS_RECEIVED_DATA = 'LISTEN_TO_PROVIDERS_RECEIVED_DATA';
export const LISTEN_TO_PROVIDERS_STARTED = 'LISTEN_TO_PROVIDERS_STARTED';
export const LISTEN_TO_PROVIDER_RECEIVED_DATA = 'LISTEN_TO_PROVIDER_RECEIVED_DATA';
export const LISTEN_TO_PROVIDER_STARTED = 'LISTEN_TO_PROVIDER_STARTED';

//Database
export const DATABASE_EDIT_STARTED = 'DATABASE_EDIT_STARTED';
export const DATABASE_EDIT_FINISH = 'DATABASE_EDIT_FINISH';

//User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
